### PR TITLE
Update README.md with R version

### LINKED ISSUE #9: The version of R in which renv.lock is created
It seems that the `renv.lock` is created using `R 4.4`. I had an older version R `4.1` on linux and couldnot install some of the dependencies using `Rscript -e "renv::restore()"`. After installing the newest version, the installation was successful. So, we can document the version of R in the readme.

### PR DESCRIPTION
**Pull request by fnattino**
Closes #9

### CODE REVIEW

**Review by SarahAlidoost — CHANGES_REQUESTED** [review]
@fnattino please see the relevant issue #11. Can readme be updated in this PR to address #11 too? thanks

**Comment by fnattino** [comment]
Also added instructions to install from conda and to add a repository that includes linux binaries.

**Comment by fnattino** [comment]
So this should close #11 as well.

**Review by SarahAlidoost — APPROVED** [review]
@fnattino thanks, it looks good. I could create the conda environment, but I cannot test the other approach for linux users. That can be done using a github action later.

**Pull request merged**
