### PR TITLE
River valley delineation

### PR DESCRIPTION
**Pull request by rogerkuou**
Solve #6 

Explored the `rgrass` solution, but it turned out that the installation of GRASS returns error, same as Claudiu also experienced in #1. 

Further explored the approach based on the `costDist` function in `Terra`. In the original version, the slope "percentage" is wrongly computed. And the results suffer from the building residuals in DTM. Now in the fixed version, it allows one to translate the river valley definition to the elevation gain.
We found by applying a minor low pass filter (median) to DTM (to suppress the building residuals), the performance of this approach works well.

Also added a vectorization section to covert binary river valley map to polygon.

### CODE REVIEW

**Comment by rogerkuou** [comment]
Hi @cforgaci and @fnattino, my exploration is ready for review. Feel free to make any comments!

**Comment by fnattino** [comment]
Thanks @rogerkuou! It looks like a part of the sentence in the PR description got accidentally erased:

> Explored the `rgrass` solution, but it turned out that

From discussions offline, I think you reached the same conclusion as @cforgaci in #1 (getting rgrass to work with GRASSGIS was far from straightforward), correct?

**Comment by rogerkuou** [comment]
> Thanks @rogerkuou! It looks like a part of the sentence in the PR description got accidentally erased:
> 
> > Explored the `rgrass` solution, but it turned out that
> 
> From discussions offline, I think you reached the same conclusion as @cforgaci in #1 (getting rgrass to work with GRASSGIS was far from straightforward), correct?

I updated the original PR description. Thanks for the remind!

Yes, for `rgrass` the conclusion is the same as Claudiu mentioned in #1.

**Review by fnattino — APPROVED** [review]
Thanks @rogerkuou, sorry for the delayed review. It is nice that now we have a clearer understanding of what `costDist` actually returns, i.e. the accumulated  elevation from the source to each grid cell! For me, this can be merged.  

I see you mentioned the conversion of the raster to vector, but I think this has not been touched so far - maybe open an issue to remind us that this task is still pending?

**Comment by rogerkuou** [comment]
> Thanks @rogerkuou, sorry for the delayed review. It is nice that now we have a clearer understanding of what `costDist` actually returns, i.e. the accumulated elevation from the source to each grid cell! For me, this can be merged.
> 
> I see you mentioned the conversion of the raster to vector, but I think this has not been touched so far - maybe open an issue to remind us that this task is still pending?

Sorry forgot to push this! Just did. This is just a very simple vectorization. If you think there is more need to be done, I will create a new issue for this.

**Pull request merged**
